'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and

then add one more letter at a random position.

Find the letter that was added in t.
'''

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        count = dict()
        for i in t:
            count[i] = count.get(i, 0) + 1
        for j in s:
            if count.has_key(j):
                count[j] -= 1
        for item in count:
            if count[item] > 0:
                return item


